// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjykwhwotdvdrlfrwqor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqeWt3aHdvdGR2ZHJsZnJ3cW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDQxNTMsImV4cCI6MjA3MDI4MDE1M30.b_k7J4Tm8YPi_oPBWwU0xB9pFIokiMkkFwKYxixY6s4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});